#!/bin/bash

MAINDIR="/opt/terraria"
WORLDDIR="$MAINDIR/worlds"
SERVERDIR="$MAINDIR/server"
BACKUPDIR="$MAINDIR/backups"

error() {
  echo "$@" 1>&2
}

isworldrunning() {
  (screen -list | grep -q "terraria-$1") &>/dev/null
  return $?
}

isworldstarted() {
  if [[ -f "$WORLDDIR/$1/screenlog.0" && `tail -n 400 "$WORLDDIR/$1/screenlog.0" | grep '^: .*$' | wc -l` -gt "0" && ! `tail -n 400 "$WORLDDIR/$1/screenlog.0" | grep '^[^<>]*exit\s*$' | wc -l` -gt "0" ]]; then
    return 0
  fi
  return 1
}

getworldoption() {
  cat "$WORLDDIR/$1/serverconfig.txt" | grep "^\s*#*\s*$2\s*=\s*.*$" | sed "s|^\s*#*\s*$2\s*=\s*\(.*\)$|\1|"
}

getworldplayerscurrent() {
  JOINED=`cat "$WORLDDIR/$1/screenlog.0" | grep '^[^<>]*has joined\.\s*$' | wc -l`
  LEFT=`cat "$WORLDDIR/$1/screenlog.0" | grep '^[^<>]*has left\.\s*$' | wc -l`
  echo $(($JOINED-$LEFT))
}

getworldmemory() {
  PID=`screen -list | grep "terraria-$1" | sed 's|^\s*\([0-9]*\)\..*$|\1|'`
  if [ -z $PID ]; then
    echo "0 kB"
  else
    printf "%d kB\n" `ps --no-headers -p $PID -o rss`
  fi
}

getworlds() {
  if [ -z "$1" ]; then
    ls "$WORLDDIR" 2>/dev/null
  else
    echo "$1"
  fi
}

getworldsRunning() {
  if [ -z "$1" ]; then
    screen -list | grep 'terraria-' | sed 's|^.*\.terraria-\([^[:blank:]]*\).*$|\1|' | perl -pe 's/\n/ /' | perl -pe 's/(.*) $/\1\n/'
  else
    echo "$1"
  fi
}

getworldsStopped() {
  if [ -z "$1" ]; then
    WORLDS=""
    for WORLD in `getworlds`; do
      if ! isworldrunning "$WORLD"; then
        WORLDS+="$WORLD "
      fi
    done
    echo "$WORLDS" | perl -pe 's/(.*) $/\1/'
  else
    echo "$1"
  fi
}

start() {
  if [ ! -d "$WORLDDIR/$1" ]; then
    error "World not found"
    return 1
  fi
  if isworldrunning "$1"; then
    error "World already running"
    return 0
  fi

  cd "$WORLDDIR/$1"
  rm -f "$WORLDDIR/$1"/screenlog.*
  if ! screen -L -dmS "terraria-$1" /bin/bash -c "\"$SERVERDIR/TerrariaServer.bin.x86_64\" -config \"$WORLDDIR/$1/serverconfig.txt\""; then
    cd "$MAINDIR"
    error "Could not start server"
    return 1
  fi
  cd "$MAINDIR"
  while ! isworldrunning "$1"; do
    sleep 1
  done
}

stop() {
  if ! isworldrunning "$1"; then
    error "World not running"
    return 0
  fi

  WAIT=0
  while ! isworldstarted "$1" && [[ -z $2 || $WAIT -le $2 ]]; do
    WAIT=$(($WAIT+1))
    sleep 1
  done
  if ! send "$1" "exit"; then
    error "Could not stop server"
    return 1
  fi
  WAIT=0
  while isworldrunning "$1" && [[ -z $2 || $WAIT -le $2 ]]; do
    WAIT=$(($WAIT+1))
    sleep 1
  done
}

forceStop() {
  TIMEOUT="16"
  stop "$1" "$TIMEOUT"
  sleep 1
  if isworldrunning "$1"; then
    echo "Quitting server screen"
    screen -XS "terraria-$1" quit
    WAIT=0
    while isworldrunning "$1" && [ $WAIT -le $TIMEOUT ]; do
      WAIT=$(($WAIT+1))
      sleep 1
    done
    echo "Killing server screen"
    screen -XS "terraria-$1" kill
    WAIT=0
    while isworldrunning "$1" && [ $WAIT -le $TIMEOUT ]; do
      WAIT=$(($WAIT+1))
      sleep 1
    done
  fi
}

backup() {
  if [ ! -d "$WORLDDIR/$1" ]; then
    error "World not found"
    return 1
  fi

  if isworldstarted "$1"; then
    if ! send "$1" "save"; then
      error "Could not save server"
      return 1
    fi
    sleep 5
  fi

  mkdir -p "$BACKUPDIR"
  if ! rdiff-backup --print-statistics "$WORLDDIR/$1" "$BACKUPDIR/$1" > "$WORLDDIR/$1/lastbackup.log"; then
    error "Could not backup server"
    return 1
  fi
  if ! rdiff-backup --remove-older-than 15D --force "$BACKUPDIR/$1" >> "$WORLDDIR/$1/lastbackup.log"; then
    error "Could not backup server"
    return 1
  fi
}

list() {
  printf "$1: "
  if isworldstarted "$1"; then
    echo "started"
  elif isworldrunning "$1"; then
    echo "starting/stopping"
  else
    echo "stopped"
  fi

  if [ ! -d "$WORLDDIR/$1" ]; then
    echo "  World folder not found"

  else
    CURRENT=`getworldplayerscurrent "$1"`
    MAX=`getworldoption "$1" "maxplayers"`
    echo "  $CURRENT of $MAX players online"
    MEMORY=`getworldmemory "$1"`
    echo "  Used Memory: $MEMORY"
    MOTD=`getworldoption "$1" "motd"`
    echo "  Motd: '$MOTD'"
    SIZE=`getworldoption "$1" "autocreate"`
    echo "  Size: '$SIZE'"
    DIFFICULTY=`getworldoption "$1" "difficulty"`
    echo "  Difficulty: '$DIFFICULTY'"
    PORT=`getworldoption "$1" "port"`
    echo "  Port: '$PORT'"
  fi
}

create() {
  if [ -e "$WORLDDIR/$1" ]; then
    error "World already exists"
    return 1
  fi

  mkdir -p "$WORLDDIR/$1"
  cp "$MAINDIR/defaultserverconfig.txt" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(world\s*=\s*\).*$|\1$WORLDDIR/$1/$1.wld|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(worldpath\s*=\s*\).*$|\1$WORLDDIR/$1/|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(worldname\s*=\s*\).*$|\1$1|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(autocreate\s*=\s*\).*$|\1$2|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(difficulty\s*=\s*\).*$|\1$3|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(port\s*=\s*\).*$|\1$4|" "$WORLDDIR/$1/serverconfig.txt"
}

send() {
  if ! isworldstarted "$1"; then
    error "World not started"
    return 1
  fi

  if ! screen -S "terraria-$1" -X stuff "$2\r"; then
    error "Could not send command"
    return 1
  fi
}

attach() {
  if ! isworldrunning "$1"; then
    error "World not running"
    return 1
  fi

  script /dev/null -qc "screen -r \"terraria-$1\""
  return $?
}

update() {
  rm -rf "$SERVERDIR"
  DOWNLOAD=`curl -s "https://terraria.gamepedia.com/Server" | perl -pe 's/\n//' | sed 's|.*\(https*://terraria.org/server/.*\.zip\).*|\1|'`
  curl -so "$MAINDIR/server.zip" "$DOWNLOAD"
  unzip -q "$MAINDIR/server.zip" -d "$SERVERDIR.tmp"
  rm -f "$MAINDIR/server.zip"
  VERSIONFOLDER=`ls "$SERVERDIR.tmp"`
  mv "$SERVERDIR.tmp/$VERSIONFOLDER/Linux" "$SERVERDIR"
  rm -rf "$SERVERDIR.tmp"
  chmod +x "$SERVERDIR/TerrariaServer.bin.x86"
  chmod +x "$SERVERDIR/TerrariaServer.bin.x86_64"
}

case "$1" in

  start)
    for WORLD in `getworldsStopped "$2"`; do
      echo "-- Starting world: $WORLD"
      start "$WORLD"
    done
  ;;

  stop)
    for WORLD in `getworldsRunning "$2"`; do
      echo "-- Stopping world: $WORLD"
      stop "$WORLD"
    done
  ;;

  force-stop)
    for WORLD in `getworldsRunning "$2"`; do
      echo "-- Stopping world: $WORLD"
      forceStop "$WORLD"
    done
  ;;

  restart)
    if [ ! -z "$2" ]; then
      echo "-- Restarting world: $2"
      if stop "$2"; then
        start "$2"
      fi

    elif "$0" stop; then
      "$0" start
    fi
  ;;

  force-restart)
    if [ ! -z "$2" ]; then
      echo "-- Restarting world: $2"
      if force-stop "$2"; then
        start "$2"
      fi

    elif "$0" force-stop; then
      "$0" start
    fi
  ;;

  backup)
    for WORLD in `getworlds "$2"`; do
      echo "-- Backing up world: $WORLD"
      backup "$WORLD"
    done
  ;;

  list)
    for WORLD in `getworlds "$2"`; do
      list "$WORLD"
    done
  ;;

  send)
    if [ -z "$2" ]; then
      echo "Enter the world name to send to"
      exit 1
    fi
    if [ -z "$3" ]; then
      echo "Enter a command to send"
      exit 1
    fi

    echo "-- Sending '${*:3}' to '$2'"
    send "$2" "${*:3}"
  ;;

  attach)
    if [ -z "$2" ]; then
      echo "Enter the world name to attach to"
      exit 1
    fi

    echo "-- Attaching to '$2'"
    attach "$2"
  ;;

  create)
    if [ -z "$2" ]; then
      echo "Enter a name for the new world"
      exit 1
    fi
    if [[ "$3" != "1" && "$3" != "2" && "$3" != "3" ]]; then
      echo "Enter a valid size for the new world (1, 2, 3)"
      exit 1
    fi
    if [[ "$4" != "0" && "$4" != "1" ]]; then
      echo "Enter a valid difficulty for the new world (0, 1)"
      exit 1
    fi
    PORT="$5"
    if [ -z "$PORT" ]; then
      PORT="7777"
    fi

    echo "-- Creating world: $2"
    create "$2" "$3" "$4" "$PORT"
  ;;

  update)
    if "$0" force-stop; then
      echo "Updating server..."
      if update; then
        "$0" start
      fi
    fi
  ;;

  list-worlds-all)
    getworlds
  ;;

  list-worlds-running)
    getworldsRunning
  ;;

  list-worlds-stopped)
    getworldsStopped
  ;;

  *)
    error "Unknown command or parameter"
    exit 1
  ;;

esac
exit 0
