#!/bin/bash

MAINDIR="/opt/terraria"
WORLDDIR="$MAINDIR/worlds"
SERVERDIR="$MAINDIR/server"
BACKUPDIR="$MAINDIR/backups"

error() {
  printf "\n"
  printf "  $1" 1>&2
}

isworldrunning() {
  (screen -list | grep -q "terraria-$1") &>/dev/null
  return $?
}

getworlds() {
  if [ -z "$1" ]; then
    ls "$WORLDDIR" 2>/dev/null
  else
    echo "$1"
  fi
}

start() {
  if [ ! -d "$WORLDDIR/$1" ]; then
    error "World not found"
    return 1
  fi
  if isworldrunning "$1"; then
    error "World already running"
    return 0
  fi

  if ! screen -dmS "terraria-$1" /bin/bash -c "\"$SERVERDIR/TerrariaServer.bin.x86_64\" -config \"$WORLDDIR/$1/serverconfig.txt\""; then
    error "Could not start server"
    return 1
  fi
}

stop() {
  if ! isworldrunning "$1"; then
    error "World not running"
    return 0
  fi

  if ! send "$1" "exit"; then
    error "Could not stop server"
    return 1
  fi
  while isworldrunning "$1"; do
    sleep 1
  done
}

backup() {
  if [ ! -d "$WORLDDIR/$1" ]; then
    error "World not found"
    return 1
  fi

  if isworldrunning "$1"; then
    if ! send "$1" "save"; then
      error "Could not save server"
      return 1
    fi
    sleep 5
  fi

  mkdir -p "$BACKUPDIR"
  if ! rdiff-backup --print-statistics "$WORLDDIR/$1" "$BACKUPDIR/$1" > "$WORLDDIR/$1/lastbackup.log"; then
    error "Could not backup server"
    return 1
  fi
  if ! rdiff-backup --remove-older-than 15D --force "$BACKUPDIR/$1" >> "$WORLDDIR/$1/lastbackup.log"; then
    error "Could not backup server"
    return 1
  fi
}

create() {
  if [ -e "$WORLDDIR/$1" ]; then
    error "World already exists"
    return 1
  fi

  mkdir -p "$WORLDDIR/$1"
  cp "$MAINDIR/defaultserverconfig.txt" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(world\s*=\s*\).*$|\1$WORLDDIR/$1/$1.wld|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(worldpath\s*=\s*\).*$|\1$WORLDDIR/$1/|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(worldname\s*=\s*\).*$|\1$1|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(autocreate\s*=\s*\).*$|\1$2|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(difficulty\s*=\s*\).*$|\1$3|" "$WORLDDIR/$1/serverconfig.txt"
  sed -i "s|^\s*#*\s*\(port\s*=\s*\).*$|\1$4|" "$WORLDDIR/$1/serverconfig.txt"
}

send() {
  if ! isworldrunning "$1"; then
    error "World not running"
    return 1
  fi

  if ! screen -S "terraria-$1" -X stuff "$2\r"; then
    error "Could not send command"
    return 1
  fi
}

attach() {
  if ! isworldrunning "$1"; then
    error "World not running"
    return 1
  fi

  printf "\n  "
  script /dev/null -qc "screen -r \"terraria-$1\""
}

update() {
  rm -rf "$SERVERDIR"
  DOWNLOAD=`curl -s "https://terraria.gamepedia.com/Server" | perl -pe 's/\n//' | sed 's|.*\(https*://terraria.org/server/.*\.zip\).*|\1|'`
  curl -so "$MAINDIR/server.zip" "$DOWNLOAD"
  unzip -q "$MAINDIR/server.zip" -d "$SERVERDIR.tmp"
  rm -f "$MAINDIR/server.zip"
  VERSIONFOLDER=`ls "$SERVERDIR.tmp"`
  mv "$SERVERDIR.tmp/$VERSIONFOLDER/Linux" "$SERVERDIR"
  rm -rf "$SERVERDIR.tmp"
  chmod +x "$SERVERDIR/TerrariaServer.bin.x86"
  chmod +x "$SERVERDIR/TerrariaServer.bin.x86_64"
}

case "$1" in

  start)
    FAILED="true"
    for WORLD in `getworlds "$2"`; do
      if $FAILED; then
        printf "Starting world: "
        FAILED="false"
      fi
      printf "$WORLD "
      if ! start "$WORLD"; then
        printf "\n"
        FAILED="true"
      fi
    done
    if ! $FAILED; then
      printf "\n"
    fi
  ;;

  stop)
    FAILED="true"
    for WORLD in `getworlds "$2"`; do
      if $FAILED; then
        printf "Stopping world: "
        FAILED="false"
      fi
      printf "$WORLD "
      if ! stop "$WORLD"; then
        printf "\n"
        FAILED="true"
      fi
    done
    if ! $FAILED; then
      printf "\n"
    fi
  ;;

  restart)
    FAILED="true"
    for WORLD in `getworlds "$2"`; do
      if $FAILED; then
        printf "Restarting world: "
        FAILED="false"
      fi
      printf "$WORLD "
      if ! stop "$WORLD"; then
        printf "\n"
        FAILED="true"
      fi
      if ! $FAILED; then
        if ! start "$WORLD"; then
          printf "\n"
          FAILED="true"
        fi
      fi
    done
    if ! $FAILED; then
      printf "\n"
    fi
  ;;

  backup)
    FAILED="true"
    for WORLD in `getworlds "$2"`; do
      if $FAILED; then
        printf "Backing up world: "
        FAILED="false"
      fi
      printf "$WORLD "
      if ! backup "$WORLD"; then
        printf "\n"
        FAILED="true"
      fi
    done
    if ! $FAILED; then
      printf "\n"
    fi
  ;;

  send)
    if [ -z "$2" ]; then
      echo "Enter the world name to send to"
      exit 1
    fi
    if [ -z "$3" ]; then
      echo "Enter a command to send"
      exit 1
    fi

    printf "Sending '${*:3}' to '$2'"
    send "$2" "${*:3}"
    printf "\n"
  ;;

  attach)
    if [ -z "$2" ]; then
      echo "Enter the world name to attach to"
      exit 1
    fi

    printf "Attaching to '$2'"
    attach "$2"
  ;;

  create)
    if [ -z "$2" ]; then
      echo "Enter a name for the new world"
      exit 1
    fi
    if [[ "$3" != "1" && "$3" != "2" && "$3" != "3" ]]; then
      echo "Enter a valid size for the new world (1, 2, 3)"
      exit 1
    fi
    if [[ "$4" != "0" && "$4" != "1" ]]; then
      echo "Enter a valid difficulty for the new world (0, 1)"
      exit 1
    fi
    PORT="$5"
    if [ -z "$PORT" ]; then
      PORT="7777"
    fi

    printf "Creating world: $2"
    create "$2" "$3" "$4" "$PORT"
    printf "\n"
  ;;

  update)
    FAILED="false"
    if ! "$0" stop; then
      FAILED="true"
    fi
    if ! $FAILED; then
      printf "Updating server..."
      if ! update; then
        FAILED="true"
      fi
    fi
    printf "\n"
    if ! $FAILED; then
      "$0" start
    fi
  ;;

esac
exit 0
