#!/bin/sh
### BEGIN INIT INFO
# Provides:       terrariad
# Required-Start: $local_fs
# Required-Stop:  $local_fs
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Terraria Server Manager
### END INIT INFO

# Setup the default user name.
USER_NAME="terraria"

# Setup the default location.
cd /opt/terraria

# Run the main script.
if [ "$USER_NAME" = "$(whoami)" ]; then
  _terrariad $@
else
  sudo -iu $USER_NAME _terrariad $@
  exit
fi
